mklink /J /D ..\..\addons\ofxBlackmagic2 .\addons\ofxBlackmagic2
mklink /J /D ..\..\addons\ofxCvGui2 .\addons\ofxCvGui2
mklink /J /D ..\..\addons\ofxGrabCam .\addons\ofxGrabCam
mklink /J /D ..\..\addons\ofxJSON .\addons\ofxJSON
mklink /J /D ..\..\addons\ofxLiquidEvent .\addons\ofxLiquidEvent
mklink /J /D ..\..\addons\ofxUI .\addons\ofxUI
mklink /J /D ..\..\addons\ofxVideoHubControl .\addons\ofxVideoHubControl
mklink /J /D ..\..\addons\ofxVideoStreamer .\addons\ofxVideoStreamer
mklink /J /D ..\..\addons\ofxVMIG .\addons\ofxVMIG
mklink /J /D ..\..\addons\ofxWinTouch .\addons\ofxWinTouch